# -*- coding: utf-8 -*-
"""Lab2_OOP_P1_Rodriguez_Jose.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zv-lFW5WTwTMj52zxCIs_u_CGeeNsH1Z
"""

class user:
    def __init__(self, username, password, email, age=None):
        self.username = username
        self.__password = password
        self.email = email
        self.age = age

    def show_user(self):
        print(f"User: {self.username}")
        if self.age is not None:
            print(f"Age: {self.age}")

class post:
    def __init__(self, topic, content, author):
        self.topic = topic
        self.content = content
        self.author = author

    def show_post(self):
        print(f"Topic: {self.topic}")
        print(f"Content: {self.content}")
        print(f"Author: {self.author.username}")


class comment:
    def __init__(self, author, text, post):
        self.author = author
        self.text = text
        self.post = post

    def show_comment(self):
        print(f"{self.author.username}: {self.text}")
        print(f"Post: {self.post.topic}")


class message:
    def __init__(self, destinatary, receiver, content):
        self.destinatary = destinatary
        self.receiver = receiver
        self.content = content

    def show_message(self):
        print(f"From: {self.destinatary.username}")
        print(f"To: {self.receiver.username}")
        print(f"Message: {self.content}")


# USERS
user1 = user("Raul", "1234", "raul@gmail.com")
user2 = user("Joel", "5678", "joel@gmail.com")

# POST
post1 = post(
    "Python OOP",
    "Classes and objects are important.",
    user1
)

# COMMENT
comment1 = comment(
    user2,
    "Nice explanation!",
    post1
)

# MESSAGE
message1 = message(
    user2,
    user1,
    "Can you explain inheritance?"
)

# SHOW DATA
post1.show_post()
print()

comment1.show_comment()
print()

message1.show_message()